(() => {
  const sessions = document.querySelector('#sessions'), term = document.querySelector('#term'), label = document.querySelector('#label'), status = document.querySelector('#status');
  const subject = new URLSearchParams(location.search).get('subject') || 'local-test';
  let current, socket, counter = 0, state, streamId = '';
  const headerBytes = (n) => new Uint8Array([(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255]);
  const read32 = (b, o) => (((b[o]<<24)>>>0)|(b[o+1]<<16)|(b[o+2]<<8)|b[o+3])>>>0;
  const envelope = (h, payload) => { const hb = new TextEncoder().encode(JSON.stringify(h)), out = new Uint8Array(4+hb.length+payload.length); out.set(headerBytes(hb.length)); out.set(hb,4); out.set(payload,4+hb.length); return out; };
  const inner = (kind, meta, payload) => { const a = new TextEncoder().encode(kind), b = new TextEncoder().encode(JSON.stringify(Object.assign({v:2},meta))), count = payload ? 3 : 2, size = 4+4+a.length+4+b.length+(payload?4+payload.length:0), out = new Uint8Array(size), dv = new DataView(out.buffer); let o=0; dv.setUint32(o,count);o+=4;dv.setUint32(o,a.length);o+=4;out.set(a,o);o+=a.length;dv.setUint32(o,b.length);o+=4;out.set(b,o);o+=b.length;if(payload){dv.setUint32(o,payload.length);o+=4;out.set(payload,o)}return out; };
  const parse = (data) => { const b = new Uint8Array(data), hl=read32(b,0), h=JSON.parse(new TextDecoder().decode(b.slice(4,4+hl))); return {h,p:b.slice(4+hl)}; };
  const parseInner = (data) => { const b=new Uint8Array(data), dv=new DataView(b.buffer), n=dv.getUint32(0), fs=[];let o=4;for(let i=0;i<n;i++){const l=dv.getUint32(o);o+=4;fs.push(b.slice(o,o+l));o+=l}return {kind:new TextDecoder().decode(fs[0]),meta:JSON.parse(new TextDecoder().decode(fs[1])),payload:fs[2]}; };
  const textState = () => (state?.screen?.frame?.lines || []).map(row => (row||[]).map(c => c?.text || ' ').join('')).join('\n');
  const render = () => { term.textContent = textState(); term.scrollTop = term.scrollHeight; };
  const apply = async (msg) => {
    if(msg.kind === 'attached'){ const raw = new Response(new Blob([msg.payload]).stream().pipeThrough(new DecompressionStream('gzip'))); const archive=JSON.parse(await (await raw).text()); state=archive.checkpoint; for(const e of (archive.tail||[])){if(e.kind==='screen-delta') applyDelta(e.delta);state.seq=e.seq} render(); return; }
    if(msg.kind === 'screen-delta'){applyDelta(msg.payload ? JSON.parse(new TextDecoder().decode(msg.payload)) : null);state.seq=msg.meta.seq;render();}
  };
  const applyDelta = (d) => { if(!d||!state?.screen)return; const f=state.screen.frame;if(d.full||f.cols!==d.cols||f.rows!==d.rows){f.cols=d.cols;f.rows=d.rows;f.lines=[]}for(const line of (d.lines||[]))f.lines[line.y]=line.cells;f.cursor=d.cursor;f.title=d.title; };
  async function refresh(){ const r=await fetch('/sessions?namespace='+encodeURIComponent(new URLSearchParams(location.search).get('namespace')||''),{headers:{'X-Shenmux-Subject':subject}}); const list=await r.json();sessions.replaceChildren();for(const s of list){const b=document.createElement('button');b.className='session';b.innerHTML=`${s.metadata.pod||s.device_id} · ${s.session.name||s.session.id}<div class="meta">${s.metadata.harness||'agent'} · ${s.metadata.namespace||''}</div>`;b.onclick=()=>open(s);sessions.append(b)}if(!list.length)sessions.textContent='No online sessions';}
  async function open(s){ if(socket)socket.close();current=s;counter=1;streamId=crypto.randomUUID();state=null;term.textContent='connecting…';label.textContent=`${s.metadata.pod||s.device_id} / ${s.session.name||s.session.id}`;status.textContent='authorizing';const cap=await (await fetch('/capabilities',{method:'POST',headers:{'Content-Type':'application/json','X-Shenmux-Subject':subject},body:JSON.stringify({device_id:s.device_id,session_id:s.session.id,permission:'control'})})).json();const scheme=location.protocol==='https:'?'wss':'ws';socket=new WebSocket(`${scheme}://${location.host}/browser?subject=${encodeURIComponent(subject)}`);socket.binaryType='arraybuffer';socket.onopen=()=>{status.textContent='connected';const payload=new TextEncoder().encode(JSON.stringify({id:cap.id,token:cap.token,permission:cap.permission}));socket.send(envelope({v:1,type:'open',device_id:s.device_id,session_id:s.session.id,stream_id:streamId,counter:counter++},payload))};socket.onmessage=e=>{const x=parse(e.data),m=parseInner(x.p);apply(m).catch(err=>status.textContent='decode error: '+err)};socket.onclose=()=>{status.textContent='disconnected'};}
  term.addEventListener('keydown',e=>{if(!socket||socket.readyState!==1||!current)return;let d=e.key==='Enter'?'\r':e.key==='Backspace'?'\x7f':e.key.length===1?e.key:'';if(!d)return;e.preventDefault();socket.send(envelope({v:1,type:'session',device_id:current.device_id,session_id:current.session.id,stream_id:streamId,counter:counter++},inner('input',{session:current.session.id},new TextEncoder().encode(d))))});
  refresh().catch(e=>{sessions.textContent='Unable to load sessions: '+e});
})();
