package operator

import (
	"os"
	"path/filepath"
	"sort"
)

// Worker names the on-disk state layout for a single worker under
// STATE/workers/NAME/.
type Worker struct {
	State string // the --state DIR
	Name  string
}

// NewWorker returns a Worker handle.
func NewWorker(state, name string) Worker { return Worker{State: state, Name: name} }

// WorkersRoot is STATE/workers.
func WorkersRoot(state string) string { return filepath.Join(state, "workers") }

// StoreDir is the content-addressed snapshot store, STATE/store.
func StoreDir(state string) string { return filepath.Join(state, "store") }

// Dir is STATE/workers/NAME.
func (w Worker) Dir() string { return filepath.Join(WorkersRoot(w.State), w.Name) }

// Workspace is the harness working directory.
func (w Worker) Workspace() string { return filepath.Join(w.Dir(), "workspace") }

// Home is the HOME for the harness.
func (w Worker) Home() string { return filepath.Join(w.Dir(), "home") }

// SecretsPath is the worker's secrets.json.
func (w Worker) SecretsPath() string { return filepath.Join(w.Dir(), "secrets.json") }

// ProxyCADir holds ca.crt/ca.key generated by secret-proxy.
func (w Worker) ProxyCADir() string { return filepath.Join(w.Dir(), "proxy-ca") }

// ProxyCACert is the CA cert path child processes must trust.
func (w Worker) ProxyCACert() string { return filepath.Join(w.ProxyCADir(), "ca.crt") }

// ManifestsDir holds the checkpoint chain.
func (w Worker) ManifestsDir() string { return filepath.Join(w.Dir(), "manifests") }

// HistoryDir is the shenmux session history directory.
func (w Worker) HistoryDir() string { return filepath.Join(w.Dir(), "shenmux-history") }

// TranscriptLog is the harness's plain-text transcript, mirrored from the PTY
// stdout that shenmux owns, so headless tooling can read it without decoding
// the shenmux history archive.
func (w Worker) TranscriptLog() string { return filepath.Join(w.Workspace(), "agent.log") }

// SessionLog is the combined worker session output.
func (w Worker) SessionLog() string { return filepath.Join(w.Dir(), "session.log") }

// ProxyLog is the secret-proxy log.
func (w Worker) ProxyLog() string { return filepath.Join(w.Dir(), "proxy.log") }

// StatusPath is the worker's status.json.
func (w Worker) StatusPath() string { return filepath.Join(w.Dir(), "status.json") }

// EventsPath is the worker's events.ndjson.
func (w Worker) EventsPath() string { return filepath.Join(w.Dir(), "events.ndjson") }

// Exists reports whether the worker directory exists.
func (w Worker) Exists() bool {
	fi, err := os.Stat(w.Dir())
	return err == nil && fi.IsDir()
}

// EnsureDirs creates all the directories in the worker layout.
func (w Worker) EnsureDirs() error {
	for _, d := range []string{
		w.Workspace(),
		w.Home(),
		w.ProxyCADir(),
		w.ManifestsDir(),
		w.HistoryDir(),
	} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			return err
		}
	}
	return nil
}

// ReadStatus loads status.json.
func (w Worker) ReadStatus() (*Status, error) {
	var st Status
	if err := ReadJSONFile(w.StatusPath(), &st); err != nil {
		return nil, err
	}
	return &st, nil
}

// WriteStatus persists status.json.
func (w Worker) WriteStatus(st *Status) error {
	return WriteJSONFile(w.StatusPath(), st)
}

// LatestManifest returns the newest manifest path in ManifestsDir, or "" if
// there are no checkpoints yet.
func (w Worker) LatestManifest() (string, error) {
	entries, err := os.ReadDir(w.ManifestsDir())
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	var names []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		if filepath.Ext(e.Name()) == ".sexpr" {
			names = append(names, e.Name())
		}
	}
	if len(names) == 0 {
		return "", nil
	}
	// Manifest filenames are timestamp-prefixed, so lexical sort == chronological.
	sort.Strings(names)
	return filepath.Join(w.ManifestsDir(), names[len(names)-1]), nil
}

// ListWorkers returns the names of all workers under STATE, sorted.
func ListWorkers(state string) ([]string, error) {
	entries, err := os.ReadDir(WorkersRoot(state))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var names []string
	for _, e := range entries {
		if e.IsDir() {
			names = append(names, e.Name())
		}
	}
	sort.Strings(names)
	return names, nil
}
