package main

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"os/signal"
	"sync/atomic"
	"syscall"
	"time"

	muxclient "github.com/pyrex41/shenmux/client"
	"github.com/pyrex41/shenmux/internal/naming"
	"github.com/pyrex41/shenmux/internal/screen"
	"github.com/pyrex41/shenmux/internal/ttyx"
)

const detachByte = byte(0x1d) // Ctrl-]

func main() {
	code, err := run(os.Args[1:])
	if err != nil {
		fmt.Fprintln(os.Stderr, "muxctl:", err)
		if code == 0 {
			code = 1
		}
	}
	os.Exit(code)
}

func run(args []string) (int, error) {
	flags := flag.NewFlagSet("muxctl", flag.ContinueOnError)
	flags.SetOutput(os.Stderr)
	session := flags.String("session", "default", "session name")
	clientID := flags.String("client", "", "client identity (generated by default)")
	control := flags.String("control", "", "ZeroMQ control endpoint")
	data := flags.String("data", "", "ZeroMQ data endpoint")
	noRaw := flags.Bool("no-raw", false, "do not put stdin in raw mode")
	observe := flags.Bool("observe", false, "attach read-only instead of acquiring the exclusive input/resize lease")
	flags.Usage = func() {
		fmt.Fprintf(flags.Output(), "usage: muxctl [flags]\n\nAttach to a shenmux session. Press Ctrl-] to detach locally.\n\n")
		flags.PrintDefaults()
	}
	if err := flags.Parse(args); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return 0, nil
		}
		return 2, err
	}
	if err := naming.ValidateSession(*session); err != nil {
		return 2, err
	}
	defaultControl, defaultData, err := naming.DefaultEndpoints(*session)
	if err != nil {
		return 2, err
	}
	if *control == "" {
		*control = defaultControl
	}
	if *data == "" {
		*data = defaultData
	}
	if *clientID == "" {
		*clientID = generatedClientID()
	}

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	client, err := muxclient.New(ctx, muxclient.Config{
		Session: *session, ClientID: *clientID,
		ControlEndpoint: *control, DataEndpoint: *data,
	})
	if err != nil {
		return 1, err
	}
	defer client.Close()

	var raw *ttyx.State
	if !*noRaw && ttyx.IsTerminal(os.Stdin.Fd()) {
		raw, err = ttyx.MakeRaw(os.Stdin.Fd())
		if err != nil {
			return 1, err
		}
		defer raw.Restore()
	}

	attachCtx, cancelAttach := context.WithTimeout(ctx, 5*time.Second)
	snapshot, err := client.Attach(attachCtx)
	cancelAttach()
	if err != nil {
		return 1, err
	}
	view := snapshot.View()
	renderer := &screen.Renderer{}
	if err := snapshot.Render(os.Stdout, renderer); err != nil {
		return 1, err
	}
	if view.Checkpoint.Exited {
		return view.Checkpoint.ExitCode, nil
	}

	var hasControl atomic.Bool
	if !*observe {
		leaseCtx, cancel := context.WithTimeout(ctx, 5*time.Second)
		meta, acquireErr := client.AcquireControl(leaseCtx)
		cancel()
		if acquireErr != nil {
			return 1, fmt.Errorf("acquire exclusive control (use --observe for read-only attachment): %w", acquireErr)
		}
		hasControl.Store(meta.HasControl)
	} else {
		hasControl.Store(view.HasControl(client.ID()))
	}

	if hasControl.Load() {
		if cols, rows, sizeErr := ttyx.Size(os.Stdin.Fd()); sizeErr == nil {
			if err := client.Resize(ctx, cols, rows); err != nil {
				return 1, err
			}
		}
	}
	winch := make(chan os.Signal, 1)
	signal.Notify(winch, syscall.SIGWINCH)
	defer signal.Stop(winch)
	go func() {
		for {
			select {
			case <-ctx.Done():
				return
			case <-winch:
				if !hasControl.Load() {
					continue
				}
				if cols, rows, sizeErr := ttyx.Size(os.Stdin.Fd()); sizeErr == nil {
					if resizeErr := client.Resize(ctx, cols, rows); resizeErr != nil && !errors.Is(resizeErr, context.Canceled) {
						// The event loop also receives ownership changes. Report a
						// failed resize without racing to terminate the main loop.
						fmt.Fprintln(os.Stderr, "muxctl: resize:", resizeErr)
					}
				}
			}
		}
	}()

	inputDone := make(chan error, 1)
	detach := make(chan struct{}, 1)
	go copyInput(ctx, client, &hasControl, inputDone, detach)
	events := client.Events()
	errorsCh := client.Errors()

	for {
		select {
		case <-detach:
			detachCtx, cancel := context.WithTimeout(context.Background(), time.Second)
			detachErr := client.Detach(detachCtx)
			cancel()
			return 0, detachErr
		case inputErr := <-inputDone:
			inputDone = nil
			if inputErr != nil && !errors.Is(inputErr, io.EOF) && !errors.Is(inputErr, context.Canceled) {
				return 1, inputErr
			}
		case actorErr, ok := <-errorsCh:
			if !ok {
				errorsCh = nil
				continue
			}
			if actorErr != nil {
				fmt.Fprintln(os.Stderr, "muxctl:", actorErr)
			}
		case msg, ok := <-events:
			if !ok {
				return 0, nil
			}
			if msg.Meta.Seq <= view.Checkpoint.Seq {
				continue
			}
			if msg.Meta.Seq != view.Checkpoint.Seq+1 {
				fresh, syncErr := resync(ctx, client, renderer)
				if syncErr != nil {
					return 1, syncErr
				}
				view = fresh.View()
				hasControl.Store(view.HasControl(client.ID()))
				if view.Checkpoint.Exited {
					return view.Checkpoint.ExitCode, nil
				}
				continue
			}
			delta, applyErr := view.Apply(msg)
			if applyErr != nil {
				return 1, applyErr
			}
			hasControl.Store(view.HasControl(client.ID()))
			if delta != nil {
				if err := renderer.RenderDelta(os.Stdout, view.Checkpoint.Screen, *delta); err != nil {
					return 1, err
				}
			}
			if view.Checkpoint.Exited {
				return view.Checkpoint.ExitCode, nil
			}
		case <-ctx.Done():
			return 0, nil
		}
	}
}

func resync(ctx context.Context, client *muxclient.Client, renderer *screen.Renderer) (muxclient.Snapshot, error) {
	resyncCtx, cancel := context.WithTimeout(ctx, 5*time.Second)
	fresh, err := client.Resync(resyncCtx)
	cancel()
	if err != nil {
		return muxclient.Snapshot{}, err
	}
	if err := fresh.Render(os.Stdout, renderer); err != nil {
		return muxclient.Snapshot{}, err
	}
	return fresh, nil
}

func copyInput(ctx context.Context, client *muxclient.Client, hasControl *atomic.Bool, done chan<- error, detach chan<- struct{}) {
	buffer := make([]byte, 4096)
	for {
		n, err := os.Stdin.Read(buffer)
		if n > 0 {
			detachAt := -1
			for i := 0; i < n; i++ {
				if buffer[i] == detachByte {
					detachAt = i
					break
				}
			}
			if detachAt >= 0 {
				if detachAt > 0 && hasControl.Load() {
					if sendErr := client.Input(ctx, buffer[:detachAt]); sendErr != nil {
						done <- sendErr
						return
					}
				}
				select {
				case detach <- struct{}{}:
				default:
				}
				return
			}
			if hasControl.Load() {
				if sendErr := client.Input(ctx, buffer[:n]); sendErr != nil {
					done <- sendErr
					return
				}
			}
		}
		if err != nil {
			done <- err
			return
		}
	}
}

func generatedClientID() string {
	var random [8]byte
	if _, err := rand.Read(random[:]); err != nil {
		return fmt.Sprintf("muxctl-%d-%d", os.Getpid(), time.Now().UnixNano())
	}
	return fmt.Sprintf("muxctl-%d-%s", os.Getpid(), hex.EncodeToString(random[:]))
}
